# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bitgn/vm/mini.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bitgn.vm.mini_pb2 as bitgn_dot_vm_dot_mini__pb2
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MiniRuntime(Protocol):
    async def outline(self, request: bitgn_dot_vm_dot_mini__pb2.OutlineRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.OutlineResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def search(self, request: bitgn_dot_vm_dot_mini__pb2.SearchRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.SearchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list(self, request: bitgn_dot_vm_dot_mini__pb2.ListRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.ListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def read(self, request: bitgn_dot_vm_dot_mini__pb2.ReadRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.ReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def write(self, request: bitgn_dot_vm_dot_mini__pb2.WriteRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete(self, request: bitgn_dot_vm_dot_mini__pb2.DeleteRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def answer(self, request: bitgn_dot_vm_dot_mini__pb2.AnswerRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MiniRuntimeASGIApplication(ConnectASGIApplication[MiniRuntime]):
    def __init__(self, service: MiniRuntime | AsyncGenerator[MiniRuntime], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bitgn.vm.mini.MiniRuntime/Outline": Endpoint.unary(
                    method=MethodInfo(
                        name="Outline",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.OutlineRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.OutlineResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.outline,
                ),
                "/bitgn.vm.mini.MiniRuntime/Search": Endpoint.unary(
                    method=MethodInfo(
                        name="Search",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.SearchRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.SearchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.search,
                ),
                "/bitgn.vm.mini.MiniRuntime/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.ListRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.ListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
                "/bitgn.vm.mini.MiniRuntime/Read": Endpoint.unary(
                    method=MethodInfo(
                        name="Read",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.ReadRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.ReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.read,
                ),
                "/bitgn.vm.mini.MiniRuntime/Write": Endpoint.unary(
                    method=MethodInfo(
                        name="Write",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.WriteRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.write,
                ),
                "/bitgn.vm.mini.MiniRuntime/Delete": Endpoint.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.DeleteRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete,
                ),
                "/bitgn.vm.mini.MiniRuntime/Answer": Endpoint.unary(
                    method=MethodInfo(
                        name="Answer",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.AnswerRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.answer,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bitgn.vm.mini.MiniRuntime"


class MiniRuntimeClient(ConnectClient):
    async def outline(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.OutlineRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.OutlineResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Outline",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.OutlineRequest,
                output=bitgn_dot_vm_dot_mini__pb2.OutlineResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def search(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.SearchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.SearchResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Search",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.SearchRequest,
                output=bitgn_dot_vm_dot_mini__pb2.SearchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.ListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.ListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.ListRequest,
                output=bitgn_dot_vm_dot_mini__pb2.ListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def read(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.ReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.ReadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Read",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.ReadRequest,
                output=bitgn_dot_vm_dot_mini__pb2.ReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def write(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.WriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Write",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.WriteRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.DeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.DeleteRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def answer(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.AnswerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Answer",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.AnswerRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class MiniRuntimeSync(Protocol):
    def outline(self, request: bitgn_dot_vm_dot_mini__pb2.OutlineRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.OutlineResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def search(self, request: bitgn_dot_vm_dot_mini__pb2.SearchRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.SearchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list(self, request: bitgn_dot_vm_dot_mini__pb2.ListRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.ListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def read(self, request: bitgn_dot_vm_dot_mini__pb2.ReadRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_mini__pb2.ReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def write(self, request: bitgn_dot_vm_dot_mini__pb2.WriteRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete(self, request: bitgn_dot_vm_dot_mini__pb2.DeleteRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def answer(self, request: bitgn_dot_vm_dot_mini__pb2.AnswerRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MiniRuntimeWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: MiniRuntimeSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/bitgn.vm.mini.MiniRuntime/Outline": EndpointSync.unary(
                    method=MethodInfo(
                        name="Outline",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.OutlineRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.OutlineResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.outline,
                ),
                "/bitgn.vm.mini.MiniRuntime/Search": EndpointSync.unary(
                    method=MethodInfo(
                        name="Search",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.SearchRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.SearchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.search,
                ),
                "/bitgn.vm.mini.MiniRuntime/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.ListRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.ListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
                "/bitgn.vm.mini.MiniRuntime/Read": EndpointSync.unary(
                    method=MethodInfo(
                        name="Read",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.ReadRequest,
                        output=bitgn_dot_vm_dot_mini__pb2.ReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.read,
                ),
                "/bitgn.vm.mini.MiniRuntime/Write": EndpointSync.unary(
                    method=MethodInfo(
                        name="Write",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.WriteRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.write,
                ),
                "/bitgn.vm.mini.MiniRuntime/Delete": EndpointSync.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.DeleteRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete,
                ),
                "/bitgn.vm.mini.MiniRuntime/Answer": EndpointSync.unary(
                    method=MethodInfo(
                        name="Answer",
                        service_name="bitgn.vm.mini.MiniRuntime",
                        input=bitgn_dot_vm_dot_mini__pb2.AnswerRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.answer,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bitgn.vm.mini.MiniRuntime"


class MiniRuntimeClientSync(ConnectClientSync):
    def outline(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.OutlineRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.OutlineResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Outline",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.OutlineRequest,
                output=bitgn_dot_vm_dot_mini__pb2.OutlineResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def search(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.SearchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.SearchResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Search",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.SearchRequest,
                output=bitgn_dot_vm_dot_mini__pb2.SearchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.ListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.ListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.ListRequest,
                output=bitgn_dot_vm_dot_mini__pb2.ListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def read(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.ReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_mini__pb2.ReadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Read",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.ReadRequest,
                output=bitgn_dot_vm_dot_mini__pb2.ReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def write(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.WriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Write",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.WriteRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.DeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.DeleteRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def answer(
        self,
        request: bitgn_dot_vm_dot_mini__pb2.AnswerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Answer",
                service_name="bitgn.vm.mini.MiniRuntime",
                input=bitgn_dot_vm_dot_mini__pb2.AnswerRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
