# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bitgn/vm/pcm.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bitgn.vm.pcm_pb2 as bitgn_dot_vm_dot_pcm__pb2


class PcmRuntime(Protocol):
    async def read(self, request: bitgn_dot_vm_dot_pcm__pb2.ReadRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.ReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def write(self, request: bitgn_dot_vm_dot_pcm__pb2.WriteRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.WriteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete(self, request: bitgn_dot_vm_dot_pcm__pb2.DeleteRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.DeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def mk_dir(self, request: bitgn_dot_vm_dot_pcm__pb2.MkDirRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.MkDirResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def move(self, request: bitgn_dot_vm_dot_pcm__pb2.MoveRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.MoveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list(self, request: bitgn_dot_vm_dot_pcm__pb2.ListRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.ListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def tree(self, request: bitgn_dot_vm_dot_pcm__pb2.TreeRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.TreeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def find(self, request: bitgn_dot_vm_dot_pcm__pb2.FindRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.FindResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def search(self, request: bitgn_dot_vm_dot_pcm__pb2.SearchRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.SearchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def context(self, request: bitgn_dot_vm_dot_pcm__pb2.ContextRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.ContextResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def answer(self, request: bitgn_dot_vm_dot_pcm__pb2.AnswerRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.AnswerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PcmRuntimeASGIApplication(ConnectASGIApplication[PcmRuntime]):
    def __init__(self, service: PcmRuntime | AsyncGenerator[PcmRuntime], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bitgn.vm.pcm.PcmRuntime/Read": Endpoint.unary(
                    method=MethodInfo(
                        name="Read",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.ReadRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.ReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.read,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Write": Endpoint.unary(
                    method=MethodInfo(
                        name="Write",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.WriteRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.WriteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.write,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Delete": Endpoint.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.DeleteRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.DeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete,
                ),
                "/bitgn.vm.pcm.PcmRuntime/MkDir": Endpoint.unary(
                    method=MethodInfo(
                        name="MkDir",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.MkDirRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.MkDirResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.mk_dir,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Move": Endpoint.unary(
                    method=MethodInfo(
                        name="Move",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.MoveRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.MoveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.move,
                ),
                "/bitgn.vm.pcm.PcmRuntime/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.ListRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.ListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Tree": Endpoint.unary(
                    method=MethodInfo(
                        name="Tree",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.TreeRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.TreeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.tree,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Find": Endpoint.unary(
                    method=MethodInfo(
                        name="Find",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.FindRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.FindResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.find,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Search": Endpoint.unary(
                    method=MethodInfo(
                        name="Search",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.SearchRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.SearchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.search,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Context": Endpoint.unary(
                    method=MethodInfo(
                        name="Context",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.ContextRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.ContextResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.context,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Answer": Endpoint.unary(
                    method=MethodInfo(
                        name="Answer",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.AnswerRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.AnswerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.answer,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bitgn.vm.pcm.PcmRuntime"


class PcmRuntimeClient(ConnectClient):
    async def read(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.ReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.ReadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Read",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.ReadRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.ReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def write(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.WriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.WriteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Write",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.WriteRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.WriteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.DeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.DeleteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.DeleteRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.DeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def mk_dir(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.MkDirRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.MkDirResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MkDir",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.MkDirRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.MkDirResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def move(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.MoveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.MoveResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Move",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.MoveRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.MoveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.ListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.ListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.ListRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.ListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def tree(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.TreeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.TreeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Tree",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.TreeRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.TreeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def find(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.FindRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.FindResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Find",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.FindRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.FindResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def search(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.SearchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.SearchResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Search",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.SearchRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.SearchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def context(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.ContextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.ContextResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Context",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.ContextRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.ContextResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def answer(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.AnswerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.AnswerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Answer",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.AnswerRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.AnswerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class PcmRuntimeSync(Protocol):
    def read(self, request: bitgn_dot_vm_dot_pcm__pb2.ReadRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.ReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def write(self, request: bitgn_dot_vm_dot_pcm__pb2.WriteRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.WriteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete(self, request: bitgn_dot_vm_dot_pcm__pb2.DeleteRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.DeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def mk_dir(self, request: bitgn_dot_vm_dot_pcm__pb2.MkDirRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.MkDirResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def move(self, request: bitgn_dot_vm_dot_pcm__pb2.MoveRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.MoveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list(self, request: bitgn_dot_vm_dot_pcm__pb2.ListRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.ListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def tree(self, request: bitgn_dot_vm_dot_pcm__pb2.TreeRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.TreeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def find(self, request: bitgn_dot_vm_dot_pcm__pb2.FindRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.FindResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def search(self, request: bitgn_dot_vm_dot_pcm__pb2.SearchRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.SearchResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def context(self, request: bitgn_dot_vm_dot_pcm__pb2.ContextRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.ContextResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def answer(self, request: bitgn_dot_vm_dot_pcm__pb2.AnswerRequest, ctx: RequestContext) -> bitgn_dot_vm_dot_pcm__pb2.AnswerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PcmRuntimeWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: PcmRuntimeSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/bitgn.vm.pcm.PcmRuntime/Read": EndpointSync.unary(
                    method=MethodInfo(
                        name="Read",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.ReadRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.ReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.read,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Write": EndpointSync.unary(
                    method=MethodInfo(
                        name="Write",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.WriteRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.WriteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.write,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Delete": EndpointSync.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.DeleteRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.DeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete,
                ),
                "/bitgn.vm.pcm.PcmRuntime/MkDir": EndpointSync.unary(
                    method=MethodInfo(
                        name="MkDir",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.MkDirRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.MkDirResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.mk_dir,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Move": EndpointSync.unary(
                    method=MethodInfo(
                        name="Move",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.MoveRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.MoveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.move,
                ),
                "/bitgn.vm.pcm.PcmRuntime/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.ListRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.ListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Tree": EndpointSync.unary(
                    method=MethodInfo(
                        name="Tree",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.TreeRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.TreeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.tree,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Find": EndpointSync.unary(
                    method=MethodInfo(
                        name="Find",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.FindRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.FindResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.find,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Search": EndpointSync.unary(
                    method=MethodInfo(
                        name="Search",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.SearchRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.SearchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.search,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Context": EndpointSync.unary(
                    method=MethodInfo(
                        name="Context",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.ContextRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.ContextResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.context,
                ),
                "/bitgn.vm.pcm.PcmRuntime/Answer": EndpointSync.unary(
                    method=MethodInfo(
                        name="Answer",
                        service_name="bitgn.vm.pcm.PcmRuntime",
                        input=bitgn_dot_vm_dot_pcm__pb2.AnswerRequest,
                        output=bitgn_dot_vm_dot_pcm__pb2.AnswerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.answer,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bitgn.vm.pcm.PcmRuntime"


class PcmRuntimeClientSync(ConnectClientSync):
    def read(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.ReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.ReadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Read",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.ReadRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.ReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def write(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.WriteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.WriteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Write",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.WriteRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.WriteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.DeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.DeleteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.DeleteRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.DeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def mk_dir(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.MkDirRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.MkDirResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MkDir",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.MkDirRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.MkDirResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def move(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.MoveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.MoveResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Move",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.MoveRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.MoveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.ListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.ListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.ListRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.ListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def tree(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.TreeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.TreeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Tree",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.TreeRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.TreeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def find(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.FindRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.FindResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Find",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.FindRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.FindResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def search(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.SearchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.SearchResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Search",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.SearchRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.SearchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def context(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.ContextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.ContextResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Context",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.ContextRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.ContextResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def answer(
        self,
        request: bitgn_dot_vm_dot_pcm__pb2.AnswerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_vm_dot_pcm__pb2.AnswerResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Answer",
                service_name="bitgn.vm.pcm.PcmRuntime",
                input=bitgn_dot_vm_dot_pcm__pb2.AnswerRequest,
                output=bitgn_dot_vm_dot_pcm__pb2.AnswerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
