# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bitgn/harness.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bitgn.harness_pb2 as bitgn_dot_harness__pb2


class HarnessService(Protocol):
    async def status(self, request: bitgn_dot_harness__pb2.StatusRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_benchmark(self, request: bitgn_dot_harness__pb2.GetBenchmarkRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.GetBenchmarkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def start_run(self, request: bitgn_dot_harness__pb2.StartRunRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StartRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_run(self, request: bitgn_dot_harness__pb2.GetRunRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.GetRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def submit_run(self, request: bitgn_dot_harness__pb2.SubmitRunRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.SubmitRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def start_playground(self, request: bitgn_dot_harness__pb2.StartPlaygroundRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StartPlaygroundResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def start_trial(self, request: bitgn_dot_harness__pb2.StartTrialRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StartTrialResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_trial(self, request: bitgn_dot_harness__pb2.GetTrialRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.GetTrialResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def end_trial(self, request: bitgn_dot_harness__pb2.EndTrialRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.EndTrialResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HarnessServiceASGIApplication(ConnectASGIApplication[HarnessService]):
    def __init__(self, service: HarnessService | AsyncGenerator[HarnessService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bitgn.harness.HarnessService/Status": Endpoint.unary(
                    method=MethodInfo(
                        name="Status",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StatusRequest,
                        output=bitgn_dot_harness__pb2.StatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.status,
                ),
                "/bitgn.harness.HarnessService/GetBenchmark": Endpoint.unary(
                    method=MethodInfo(
                        name="GetBenchmark",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.GetBenchmarkRequest,
                        output=bitgn_dot_harness__pb2.GetBenchmarkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_benchmark,
                ),
                "/bitgn.harness.HarnessService/StartRun": Endpoint.unary(
                    method=MethodInfo(
                        name="StartRun",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StartRunRequest,
                        output=bitgn_dot_harness__pb2.StartRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.start_run,
                ),
                "/bitgn.harness.HarnessService/GetRun": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRun",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.GetRunRequest,
                        output=bitgn_dot_harness__pb2.GetRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_run,
                ),
                "/bitgn.harness.HarnessService/SubmitRun": Endpoint.unary(
                    method=MethodInfo(
                        name="SubmitRun",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.SubmitRunRequest,
                        output=bitgn_dot_harness__pb2.SubmitRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.submit_run,
                ),
                "/bitgn.harness.HarnessService/StartPlayground": Endpoint.unary(
                    method=MethodInfo(
                        name="StartPlayground",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StartPlaygroundRequest,
                        output=bitgn_dot_harness__pb2.StartPlaygroundResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.start_playground,
                ),
                "/bitgn.harness.HarnessService/StartTrial": Endpoint.unary(
                    method=MethodInfo(
                        name="StartTrial",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StartTrialRequest,
                        output=bitgn_dot_harness__pb2.StartTrialResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.start_trial,
                ),
                "/bitgn.harness.HarnessService/GetTrial": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTrial",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.GetTrialRequest,
                        output=bitgn_dot_harness__pb2.GetTrialResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_trial,
                ),
                "/bitgn.harness.HarnessService/EndTrial": Endpoint.unary(
                    method=MethodInfo(
                        name="EndTrial",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.EndTrialRequest,
                        output=bitgn_dot_harness__pb2.EndTrialResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.end_trial,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bitgn.harness.HarnessService"


class HarnessServiceClient(ConnectClient):
    async def status(
        self,
        request: bitgn_dot_harness__pb2.StatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Status",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StatusRequest,
                output=bitgn_dot_harness__pb2.StatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_benchmark(
        self,
        request: bitgn_dot_harness__pb2.GetBenchmarkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.GetBenchmarkResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBenchmark",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.GetBenchmarkRequest,
                output=bitgn_dot_harness__pb2.GetBenchmarkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def start_run(
        self,
        request: bitgn_dot_harness__pb2.StartRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StartRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartRun",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StartRunRequest,
                output=bitgn_dot_harness__pb2.StartRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_run(
        self,
        request: bitgn_dot_harness__pb2.GetRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.GetRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRun",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.GetRunRequest,
                output=bitgn_dot_harness__pb2.GetRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def submit_run(
        self,
        request: bitgn_dot_harness__pb2.SubmitRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.SubmitRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SubmitRun",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.SubmitRunRequest,
                output=bitgn_dot_harness__pb2.SubmitRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def start_playground(
        self,
        request: bitgn_dot_harness__pb2.StartPlaygroundRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StartPlaygroundResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartPlayground",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StartPlaygroundRequest,
                output=bitgn_dot_harness__pb2.StartPlaygroundResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def start_trial(
        self,
        request: bitgn_dot_harness__pb2.StartTrialRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StartTrialResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartTrial",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StartTrialRequest,
                output=bitgn_dot_harness__pb2.StartTrialResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_trial(
        self,
        request: bitgn_dot_harness__pb2.GetTrialRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.GetTrialResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTrial",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.GetTrialRequest,
                output=bitgn_dot_harness__pb2.GetTrialResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def end_trial(
        self,
        request: bitgn_dot_harness__pb2.EndTrialRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.EndTrialResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="EndTrial",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.EndTrialRequest,
                output=bitgn_dot_harness__pb2.EndTrialResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class HarnessServiceSync(Protocol):
    def status(self, request: bitgn_dot_harness__pb2.StatusRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_benchmark(self, request: bitgn_dot_harness__pb2.GetBenchmarkRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.GetBenchmarkResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def start_run(self, request: bitgn_dot_harness__pb2.StartRunRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StartRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_run(self, request: bitgn_dot_harness__pb2.GetRunRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.GetRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def submit_run(self, request: bitgn_dot_harness__pb2.SubmitRunRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.SubmitRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def start_playground(self, request: bitgn_dot_harness__pb2.StartPlaygroundRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StartPlaygroundResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def start_trial(self, request: bitgn_dot_harness__pb2.StartTrialRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.StartTrialResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_trial(self, request: bitgn_dot_harness__pb2.GetTrialRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.GetTrialResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def end_trial(self, request: bitgn_dot_harness__pb2.EndTrialRequest, ctx: RequestContext) -> bitgn_dot_harness__pb2.EndTrialResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class HarnessServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: HarnessServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/bitgn.harness.HarnessService/Status": EndpointSync.unary(
                    method=MethodInfo(
                        name="Status",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StatusRequest,
                        output=bitgn_dot_harness__pb2.StatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.status,
                ),
                "/bitgn.harness.HarnessService/GetBenchmark": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetBenchmark",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.GetBenchmarkRequest,
                        output=bitgn_dot_harness__pb2.GetBenchmarkResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_benchmark,
                ),
                "/bitgn.harness.HarnessService/StartRun": EndpointSync.unary(
                    method=MethodInfo(
                        name="StartRun",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StartRunRequest,
                        output=bitgn_dot_harness__pb2.StartRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.start_run,
                ),
                "/bitgn.harness.HarnessService/GetRun": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRun",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.GetRunRequest,
                        output=bitgn_dot_harness__pb2.GetRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_run,
                ),
                "/bitgn.harness.HarnessService/SubmitRun": EndpointSync.unary(
                    method=MethodInfo(
                        name="SubmitRun",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.SubmitRunRequest,
                        output=bitgn_dot_harness__pb2.SubmitRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.submit_run,
                ),
                "/bitgn.harness.HarnessService/StartPlayground": EndpointSync.unary(
                    method=MethodInfo(
                        name="StartPlayground",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StartPlaygroundRequest,
                        output=bitgn_dot_harness__pb2.StartPlaygroundResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.start_playground,
                ),
                "/bitgn.harness.HarnessService/StartTrial": EndpointSync.unary(
                    method=MethodInfo(
                        name="StartTrial",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.StartTrialRequest,
                        output=bitgn_dot_harness__pb2.StartTrialResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.start_trial,
                ),
                "/bitgn.harness.HarnessService/GetTrial": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetTrial",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.GetTrialRequest,
                        output=bitgn_dot_harness__pb2.GetTrialResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_trial,
                ),
                "/bitgn.harness.HarnessService/EndTrial": EndpointSync.unary(
                    method=MethodInfo(
                        name="EndTrial",
                        service_name="bitgn.harness.HarnessService",
                        input=bitgn_dot_harness__pb2.EndTrialRequest,
                        output=bitgn_dot_harness__pb2.EndTrialResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.end_trial,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bitgn.harness.HarnessService"


class HarnessServiceClientSync(ConnectClientSync):
    def status(
        self,
        request: bitgn_dot_harness__pb2.StatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Status",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StatusRequest,
                output=bitgn_dot_harness__pb2.StatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_benchmark(
        self,
        request: bitgn_dot_harness__pb2.GetBenchmarkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.GetBenchmarkResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBenchmark",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.GetBenchmarkRequest,
                output=bitgn_dot_harness__pb2.GetBenchmarkResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def start_run(
        self,
        request: bitgn_dot_harness__pb2.StartRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StartRunResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartRun",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StartRunRequest,
                output=bitgn_dot_harness__pb2.StartRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_run(
        self,
        request: bitgn_dot_harness__pb2.GetRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.GetRunResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRun",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.GetRunRequest,
                output=bitgn_dot_harness__pb2.GetRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def submit_run(
        self,
        request: bitgn_dot_harness__pb2.SubmitRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.SubmitRunResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SubmitRun",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.SubmitRunRequest,
                output=bitgn_dot_harness__pb2.SubmitRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def start_playground(
        self,
        request: bitgn_dot_harness__pb2.StartPlaygroundRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StartPlaygroundResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartPlayground",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StartPlaygroundRequest,
                output=bitgn_dot_harness__pb2.StartPlaygroundResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def start_trial(
        self,
        request: bitgn_dot_harness__pb2.StartTrialRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.StartTrialResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartTrial",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.StartTrialRequest,
                output=bitgn_dot_harness__pb2.StartTrialResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_trial(
        self,
        request: bitgn_dot_harness__pb2.GetTrialRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.GetTrialResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTrial",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.GetTrialRequest,
                output=bitgn_dot_harness__pb2.GetTrialResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def end_trial(
        self,
        request: bitgn_dot_harness__pb2.EndTrialRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bitgn_dot_harness__pb2.EndTrialResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="EndTrial",
                service_name="bitgn.harness.HarnessService",
                input=bitgn_dot_harness__pb2.EndTrialRequest,
                output=bitgn_dot_harness__pb2.EndTrialResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
